apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: media-gateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "jellyfin.dokocloud.net,immich.dokocloud.net"
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "jellyfin.dokocloud.net"
        - "immich.dokocloud.net"
