apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jellyfin-vs
  namespace: istio-system
spec:
  hosts:
    - "jellyfin.dokocloud.net"
  gateways:
    - media-gateway
  http:
    - route:
        - destination:
            host: jellyfin.jellyfin.svc.cluster.local
            port:
              number: 8096
