apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/dokokitsune/homelab-reverse-proxy.git
    targetRevision: main
    path: infrastructure/config/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
